// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDK7ArHXf_4FOT1PjUWT5HoqHcWznkCnLs',
    appId: '1:133393390583:web:0170f9c6d527a78b04ecf2',
    messagingSenderId: '133393390583',
    projectId: 'homeiot-6640c',
    authDomain: 'homeiot-6640c.firebaseapp.com',
    databaseURL: 'https://homeiot-6640c-default-rtdb.firebaseio.com',
    storageBucket: 'homeiot-6640c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsOt7ilPdF19nOq8lhlBgTAuddgCx9CfY',
    appId: '1:133393390583:android:1d80ba9f2a88748c04ecf2',
    messagingSenderId: '133393390583',
    projectId: 'homeiot-6640c',
    databaseURL: 'https://homeiot-6640c-default-rtdb.firebaseio.com',
    storageBucket: 'homeiot-6640c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFOQv1hDx_1iAxJbrjBPQopOhJk6qzeHU',
    appId: '1:133393390583:ios:0e97f3cd8bc7bb1004ecf2',
    messagingSenderId: '133393390583',
    projectId: 'homeiot-6640c',
    databaseURL: 'https://homeiot-6640c-default-rtdb.firebaseio.com',
    storageBucket: 'homeiot-6640c.appspot.com',
    iosBundleId: 'com.example.iot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFOQv1hDx_1iAxJbrjBPQopOhJk6qzeHU',
    appId: '1:133393390583:ios:0e97f3cd8bc7bb1004ecf2',
    messagingSenderId: '133393390583',
    projectId: 'homeiot-6640c',
    databaseURL: 'https://homeiot-6640c-default-rtdb.firebaseio.com',
    storageBucket: 'homeiot-6640c.appspot.com',
    iosBundleId: 'com.example.iot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDK7ArHXf_4FOT1PjUWT5HoqHcWznkCnLs',
    appId: '1:133393390583:web:b1290aa289c9a9ff04ecf2',
    messagingSenderId: '133393390583',
    projectId: 'homeiot-6640c',
    authDomain: 'homeiot-6640c.firebaseapp.com',
    databaseURL: 'https://homeiot-6640c-default-rtdb.firebaseio.com',
    storageBucket: 'homeiot-6640c.appspot.com',
  );
}
